### ISSUE TITLE
Type error in 8.9.1

### ISSUE THREAD

**Issue by joelbarnard** [getsentry/profiling-node#245]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### SDK Version

8.9.1

### What environment is your node script running in?

Compiling with: npx tsc

### Are you using an alpine based docker image?

- [ ] Yes (please specify the version)
- [ ] No (please describe your environment)

### Does the failure occur on a remote environment only?

- [ ] Yes (please describe your environment)
- [ ] No (please describe your local environment)

### If you are using alpine, have you tried using latest version of alpine or (currently alpine3.16 or alpine3.17)?

- [ ] Yes (please specify the version)"
- [ ] No, and I cannot upgrade

### Have you tried using the latest minor version of node (currently 16.20 or 18.15)?

- [ ] Yes (please specify the version)
- [ ] No, and I cannot upgrade

### If you run npm install --verbose --foreground-scripts @sentry/profiling-node in an empty directory, what is the output?

Error when running: npx tsc 
(Works in 8.8)

file.mts:2:40 - error TS7016: Could not find a declaration file for module '@sentry/profiling-node'. '<redacted>/src/node_modules/@sentry/profiling-node/lib/esm/index.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/sentry__profiling-node` if it exists or add a new declaration (.d.ts) file containing `declare module '@sentry/profiling-node';`

2 import {nodeProfilingIntegration} from "@sentry/profiling-node";
                                         ~~~~~~~~~~~~~~~~~~~~~~~~


### Crash report

_No response_
