### ISSUE TITLE
Build broken with 1.1.x

### ISSUE THREAD

**Issue by oliversalzburg** [getsentry/profiling-node#181]
### Is there an existing issue for this?

- [X] I have checked for existing issues https://github.com/getsentry/profiling-node/issues
- [X] I have reviewed the documentation https://docs.sentry.io/
- [X] I am using the latest SDK release https://github.com/getsentry/profiling-node/releases

### How do you use Sentry?

Sentry Saas (sentry.io)

### SDK Version

1.1.1

### What environment is your node script running in?

-

### How is your code deployed and bundled?

esbuild

### Steps to Reproduce

-

### Expected Result

Build worked fine with 1.0.9, now it's broken due to the error below. Reasons seem pretty clear.

### Actual Result

```
../packages/lib-lambda/source/sentry/SentryIntegration.mts(4,38): error TS2306: File '/home/runner/work/.../node_modules/@sentry/profiling-node/lib/index.d.ts' is not a module.
```

**Comment by JonasBa** [comment]
Oh, I will investigate this asap, I changed ts build to output typedef to outfile, it should not be creating an actual import here.

You can downgrade the version meanwhile to use profiling.
